algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2020
// Seção de Declarações 
var

n1, n2: real

soma, mult, sub, divisao: real

inicio

// ENTRADA DE DADOS
ESCREVA("Digite um número: ")
LEIA(n1)

ESCREVA("Digite outro número: ")
LEIA(n2)

// PROCESSAMENTO
soma <- n1 + n2

sub <- n1 - n2

mult <- n1 * n2

divisao <- n1 / n2

// SAIDA DE DADOS
ESCREVAL("Soma: ", soma)
ESCREVAL("Subtração: ", sub)
ESCREVAL("Multiplicação: ", mult)
ESCREVAL("Divisão: ", divisao)



fimalgoritmo
