algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2020
// Seção de Declarações 
var

nome: caracter
idade: inteiro
salario: real

inicio

ESCREVA("Digite o nome do funcionario: ")
LEIA(nome)

ESCREVA("Digite a idade do funcionario: ")
LEIA(idade)

ESCREVA("Digite o salario do funcionario: ")
LEIA(salario)

ESCREVA("O funcionário ", nome," tem ", idade," anos e ganha R$ ", salario:8:2)

fimalgoritmo
