algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2020
// Seção de Declarações 
var

nome: caracter
anoNascimento, anoAtual, idade: inteiro

inicio

ESCREVA("Digite seu nome: ")
LEIA(nome)

ESCREVA("Digite seu ano de nascimento: ")
LEIA(anoNascimento)

ESCREVA("Digite o ano atual: ")
LEIA(anoAtual)

idade <- anoAtual - anoNascimento

ESCREVA(nome, " você tem ", idade," de idade")

fimalgoritmo
